---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: web-app
spec:
  minReadySeconds: 5
  replicas: 3
  selector:
    matchLabels:
      app: web-app
  template:
    metadata:
      labels:
        app: web-app
    spec:
      containers:
        - name: web-app
          image: venkeyboda/spring-framework:260
          resources:
            limits:
              cpu: 500m
              memory: 256M
            requests:
              cpu: 100m
              memory: 64M
          ports:
            - containerPort: 8080

--- 
apiVersion: v1
kind: Service
metadata:
  name: spring-svc
spec:
  selector:
    app: web-app
  type: LoadBalancer  
  ports:
  - port: 8080
    targetPort: 8080
            
